<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\BuildingBlocks\Erp.SharedKernel\Erp.SharedKernel.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Erp.Application.Abstractions\Erp.Application.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Modules\Finance\Erp.Modules.Finance.Domain\Erp.Modules.Finance.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Finance\Erp.Modules.Finance.Application\Erp.Modules.Finance.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Finance\Erp.Modules.Finance.Infrastructure\Erp.Modules.Finance.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Sales\Erp.Modules.Sales.Domain\Erp.Modules.Sales.Domain.csproj" />
  </ItemGroup>
</Project>